name: my_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  shelf: ^1.4.0
  postgres: ^3.1.0
  jaguar_jwt: ^3.0.0
  mysql1: ^0.20.0
  path: ^1.9.0
  crypto: ^3.0.3
  mailer: ^6.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

assets:
  -bin/assets